version: '3.8'

services: 
  web:
    build: .
    container_name: todolist_app
    command: python manage.py runserver 0.0.0.0:8001
    ports: 
      - "8001:8001"
    env_file: 
      - .env
    depends_on: 
      - db
  db:
    image: postgres:13.1
    container_name: todolist_db
    environment: 
      - POSTGRES_DB=todo_database
      - POSTGRES_USER=todo_user
      - POSTGRES_PASSWORD=q1w2e3r4@2021
    restart: always
    ports: 
      - "5432:5432"
